version: 1.10 #DO NOT TOUCH
Maintenance: off #This is if the maintenance option is enabled (set to 'on' to enable), BEWARE! ONLY OPs CAN JOIN IF ENABLED

joinText: We hope you enjoy this server! #This is a custom join text you can have. Comment out with # to disable

serverName: MyServer!

infoLines: 2
info1: ---- Server Name ----
info2: Site = example.com

tpa-keep-alive: 30 #in secounds
confupdate-stop: 30 #in seconds
